name: Cypress with Percy and Mochawesome

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Install Percy CLI
        run: npm install --save-dev @percy/cli

      - name: Install Mochawesome Reporter
        run: npm install --save-dev mochawesome mochawesome-merge mochawesome-report-generator

      - name: Run Cypress tests with Percy
        run: |
          npx percy exec -- npx cypress run --spec 'cypress/e2e/**/*.cy.ts'
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - name: Generate Mochawesome reports
        run: |
          # Мержим все JSON отчеты в один
          npx mochawesome-merge cypress/results/*.json > cypress/results/all-tests.json
          # Генерация финального HTML отчета
          npx mochawesome-report-generator cypress/results/all-tests.json --reportDir cypress/results --reportFilename final-report.html

          echo "HTML report has been generated!"

      - name: Remove unnecessary files (JSON and old HTML)
        run: |
          # Удаляем все промежуточные JSON файлы
          rm cypress/results/*.json
          # Удаляем старые HTML файлы, кроме финального
          rm cypress/results/*.html
          mv cypress/results/final-report.html cypress/results/mochawesome-report.html

      - name: Upload Mochawesome report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: cypress/results/mochawesome-report.html
