name: Percy Snapshot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  percy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Set up Percy token
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: echo "PERCY_TOKEN=${{ secrets.PERCY_TOKEN }}" >> $GITHUB_ENV

      - name: Run Cypress tests with Percy snapshot
        run: npx cypress run
