name: Cypress with Percy and Mochawesome

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Install Percy CLI
        run: npm install --save-dev @percy/cli

      - name: Run Cypress tests with Percy
        run: |
          npx percy exec -- npx cypress run --spec 'cypress/e2e/**/*.cy.ts'
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - name: Check JSON files are created
        run: |
          echo "Проверка наличия JSON файлов..."
          jsonFiles=$(find cypress/results -name "*.json" -not -empty)
          if [ -z "$jsonFiles" ]; then
            echo "Нет валидных JSON отчетов!"
            exit 1
          else
            echo "Найдены следующие JSON файлы:"
            echo "$jsonFiles"
          fi

      - name: Merge Mochawesome reports and generate final HTML report
        run: |
          # Проверка наличия JSON файлов в cypress/results
          jsonFiles=$(find cypress/results -name "*.json" -not -empty)
          if [ -z "$jsonFiles" ]; then
            echo "No valid JSON reports found!"
            exit 1
          fi

          # Мержим JSON файлы в один
          npx mochawesome-merge $jsonFiles > cypress/results/all-tests.json

          # Генерация финального HTML отчета
          npx mochawesome-report-generator cypress/results/all-tests.json --reportDir cypress/results --reportFilename final-report.html

          echo "HTML отчет успешно сгенерирован!"

      - name: Prepare final report and assets for download
        run: |
          # Создаем директорию для отчетов
          mkdir -p cypress/results/final_report

          # Перемещаем финальный HTML отчет в эту директорию
          mv cypress/results/final-report.html cypress/results/final_report/

          # Перемещаем папку assets в эту же директорию
          mv cypress/results/assets cypress/results/final_report/

      - name: Upload final report and assets as a single artifact
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/results/final_report/
